<?php
/**
 * Created by JetBrains PhpStorm.
 * User: SemasPing / semasping@gmail.com
 * Date: 02.12.12
 * Time: 13:10
 */

function own_import_from_file_menu() {
  $items['admin/content/own_import'] = array(
    'title' => 'Import from file',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('own_import_from_file_form'),
    'access arguments' => array('own_import_from_file'),
    'file' => '',
  );
  return $items;
}

function own_import_from_file_permission() {
  return array(
    'own_import_from_file' => array(
      'title' => t('own import from file'),
      'description' => t('own import from file')
    ),
  );
}

function own_import_from_file_form() {
  $form = array(
    '#attributes' => array('enctype' => "multipart/form-data"),
  );

  $form['import_file'] = array(
    '#type' => 'file',
    '#title' => 'Файл для импорта',
  );

  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Import')
  );



  return $form;
}

