<?php
/**
 * Created by JetBrains PhpStorm.
 * User: SemasPing / semasping@gmail.com
 * Date: 02.12.12
 * Time: 13:10
 */

function own_import_from_file_menu() {
  $items['admin/content/own_import'] = array(
    'title' => 'Import from file',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('own_import_from_file_form'),
    'access arguments' => array('own_import_from_file'),
    'file' => '',
  );
  return $items;
}

function own_import_from_file_permission() {
  return array(
    'own_import_from_file' => array(
      'title' => t('own import from file'),
      'description' => t('own import from file')
    ),
  );
}

function own_import_from_file_form() {
  $form = array(
    '#attributes' => array('enctype' => "multipart/form-data"),
  );

  $form['import_file'] = array(
    '#type' => 'file',
    '#title' => t('Excel file for import'),
  );

  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Import')
  );
  return $form;
}

function own_import_from_file_form_validate($form, &$form_state) {
  $path_parts = pathinfo($_FILES['files']['name']['import_file']);
  if (!isset($path_parts["extension"])) {
    form_set_error('import_file', t('File not choose'));
  }

  if (isset($path_parts["extension"]) && ($path_parts["extension"] != 'xlsx') && ($path_parts["extension"] != 'xls')) {
    form_set_error('import_file', t('Wrong type of file! Choose Excel file. You choose: @ext', array('@ext'=>$path_parts["extension"])));
  }
}


